<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <StartupObject>WindowsApp1.My.MyApplication</StartupObject>
    <MyType>WindowsForms</MyType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>C:\Users\pc\Dropbox\Instalador sierra\</PublishUrl>
    <Install>false</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>true</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <MinimumRequiredVersion>1.0.0.5</MinimumRequiredVersion>
    <ApplicationRevision>88</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>WindowsApp1.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <RegisterForComInterop>True</RegisterForComInterop>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineDebug>false</DefineDebug>
    <DocumentationFile>WindowsApp1.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <RegisterForComInterop>True</RegisterForComInterop>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>61792722C740D1F22D07056FFC261849EE4B5C7A</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>WindowsApp1_1_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>true</SignManifests>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>LLAVE.ico</ApplicationIcon>
    <AssemblyTitle>WindowsApp1</AssemblyTitle>
    <Product>WindowsApp1</Product>
    <Copyright>Copyright ©  2021</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <OptionCompare>Binary</OptionCompare>
  </PropertyGroup>
  <ItemGroup>
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="AliasPorProducto.Designer.vb">
      <DependentUpon>AliasPorProducto.vb</DependentUpon>
    </Compile>
    <Compile Update="BuscarEnListaDePrecios.Designer.vb">
      <DependentUpon>BuscarEnListaDePrecios.vb</DependentUpon>
    </Compile>
    <Compile Update="BusquedaProLDePrecios.Designer.vb">
      <DependentUpon>BusquedaProLDePrecios.vb</DependentUpon>
    </Compile>
    <Compile Update="Clientes.Designer.vb">
      <DependentUpon>Clientes.vb</DependentUpon>
    </Compile>
    <Compile Update="Colaboradores.Designer.vb">
      <DependentUpon>Colaboradores.vb</DependentUpon>
    </Compile>
    <Compile Update="Configuracion.Designer.vb">
      <DependentUpon>Configuracion.vb</DependentUpon>
    </Compile>
    <Compile Update="Estudios.Designer.vb">
      <DependentUpon>Estudios.vb</DependentUpon>
    </Compile>
    <Compile Update="factura.Designer.vb">
      <DependentUpon>factura.vb</DependentUpon>
    </Compile>
    <Compile Update="Facturasdecompra.Designer.vb">
      <DependentUpon>Facturasdecompra.vb</DependentUpon>
    </Compile>
    <Compile Update="FacturasDeVentas.Designer.vb">
      <DependentUpon>FacturasDeVentas.vb</DependentUpon>
    </Compile>
    <Compile Update="FormatoDeAbonosCompras.Designer.vb">
      <DependentUpon>FormatoDeAbonosCompras.vb</DependentUpon>
    </Compile>
    <Compile Update="FormatoDeAbonosVentas.Designer.vb">
      <DependentUpon>FormatoDeAbonosVentas.vb</DependentUpon>
    </Compile>
    <Compile Update="InicioDeSesion.Designer.vb">
      <DependentUpon>InicioDeSesion.vb</DependentUpon>
    </Compile>
    <Compile Update="ListaDeAlistarPelidos.Designer.vb">
      <DependentUpon>ListaDeAlistarPelidos.vb</DependentUpon>
    </Compile>
    <Compile Update="ListaDePendientes.Designer.vb">
      <DependentUpon>ListaDePendientes.vb</DependentUpon>
    </Compile>
    <Compile Update="listadeprecios.Designer.vb">
      <DependentUpon>listadeprecios.vb</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
    <Compile Update="NotasPedido.Designer.vb">
      <DependentUpon>NotasPedido.vb</DependentUpon>
    </Compile>
    <Compile Update="Proovedores.Designer.vb">
      <DependentUpon>Proovedores.vb</DependentUpon>
    </Compile>
    <Compile Update="Rutasvb.Designer.vb">
      <DependentUpon>Rutasvb.vb</DependentUpon>
    </Compile>
    <Compile Update="VerificarAlistamiento.Designer.vb">
      <DependentUpon>VerificarAlistamiento.vb</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{C0C07587-41A7-46C8-8FBD-3F9C8EBE2DDC}" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.6.1">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.6.1 %28x86 y x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Content Include="LLAVE.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="9.0.0-rc.2.24473.5" />
    <PackageReference Include="MySql.Data" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0-rc.2.24473.5" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview3.19128.7" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.4.0" />
    <PackageReference Include="System.Data.Odbc" Version="9.0.0-rc.2.24473.5" />
    <PackageReference Include="System.Data.OleDb" Version="9.0.0-rc.2.24473.5" />
    <PackageReference Include="System.Windows.Forms.DataVisualization" Version="1.0.0-prerelease.20110.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="CrystalReport1.vb" />
  </ItemGroup>
</Project>